"""usermovies table

Revision ID: 925f18707993
Revises: 39179ea2d4cf
Create Date: 2022-01-26 19:08:21.676562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925f18707993'
down_revision = '39179ea2d4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movies')
    # ### end Alembic commands ###
